[project]
name = "src"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
  "fastapi[standard]>=0.141.1",
  "pydantic-settings>=2.15.0",
  "pyjwt[crypto]>=2.14.0",
]

[dependency-groups]
dev = [
  "pytest>=9.1.1",
  "pytest-asyncio>=1.4.0",
]

[tool.ruff]
line-length = 120
target-version = "py314"

[tool.ruff.lint]
select = [
  "E",
  "F",
  "I",
  "W",
  "UP",
]
ignore = [
  "B008",
]
