name: Run Pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pytest:
    permissions:
      contents: read
      pull-requests: write  # Required to post coverage comments
    uses: joeckr/ci-templates/.github/workflows/pytest.yml@54ae02b59f073afb7522c12e8e2d420d55d6393a  # v1.20.2
    with:
      python-version: '3.14'
      working-directory: 'src'
      enable-uv: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
