name: Run Pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pytest:
    permissions:
      contents: read
      pull-requests: write  # Required to post coverage comments
    uses: joeckr/ci-templates/.github/workflows/pytest.yml@19ae34059e00de03031c56e9f7cbb98c55519719  # v1.20.1
    with:
      python-version: '3.14'
      working-directory: 'src'
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
