name: TEST Release

on:
  pull_request:
    branches: [main]

jobs:
  helm:
    permissions:
      contents: read
      packages: write
    uses: joeckr/ci-templates/.github/workflows/push-helm-ghcr.yml@54ae02b59f073afb7522c12e8e2d420d55d6393a  # v1.20.2
    with:
      charts-dir: 'chart'
      dry-run: true
  release:
    permissions:
      contents: write
    uses: joeckr/ci-templates/.github/workflows/semantic.yml@54ae02b59f073afb7522c12e8e2d420d55d6393a  # v1.20.2
    with:
      dry-run: true
  build:
    permissions:
      contents: read
      packages: write
    uses: joeckr/ci-templates/.github/workflows/build-oci.yml@54ae02b59f073afb7522c12e8e2d420d55d6393a  # v1.20.2
    with:
      image: 'skeleton-fast-api'
      version: 'test'
      dry-run: true
